apiVersion: v1
kind: Service
metadata:
  name: availability-svc
  labels:
    app: availability-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.availability.port }}
      targetPort: {{ .Values.availability.port }}
      protocol: TCP
      name: grpc
  selector:
    app: availability-svc
